### ISSUE TITLE
Time-span representation

### ISSUE THREAD

**Issue by VladimirAlexiev** [sapa/spa-specifications#1]
- crm:E61_Time_Primitive is not needed, just use a  literal with xsd data type
- use P82a,b and (more rarely) P81a,b. See the  CRM Time doc. P81 as used doesn't make it clear which is the start and which is the end
- use xsd:year rather than a pair of fake-completed dates (01-01 and 12-31). This pattern is bad because it doesn't allow to distinguish a situation where you know the real exact dates.

**Comment by birk** [comment]
When replacing `crm:E61_Time_Primitive` with a xsd literal, then wouldn't make sense to use `crm:P79_beginning_is_qualified_by` and `crm:P80_end_is_qualified_by` instead of P81 or P82?

**Comment by VladimirAlexiev** [comment]
P79, 80 are for qualifiers like circa, approx. They are not for capturing
begin_of_the_begin and end_of_the_end

**Comment by birk** [comment]
Thanks for the clarification. I implemented the first two points (replacement of `E61_Time_Primitive` and `P81_ongoing_throughout`) but ignored the third for two reasons:
- It should be possible to provide more exact dates than just years and all dates should have the same format.
- A P82a/b-time-span that starts and ends with the same year looks somewhat redundant.

https://github.com/sapa/spa-specifications/commit/35a4d59eb0fa232c33c88d933e6df55574a17bb9

**Comment by VladimirAlexiev** [comment]
> all dates should have the same format.

Why?
I think there's no strongly established best practice. But maybe:
- keep P82a/b as is, always xsd:date
- store the specific business date (not fake-completed) in P82, rdf:value or P3_has_note.

What does linked.art recommend?

**Comment by birk** [comment]
> What does linked.art recommend?

They are not really specific here. I guess for the time being, I will stay with this:

```
[ a crm:E52_Time-Span ;
	rdfs:label "1999" ;
	crm:P82a_begin_of_the_begin "1999-01-01"^^xsd:date ;
	crm:P82b_end_of_the_end "1999-12-31"^^xsd:date ]
```
